/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bowling;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BowlingTest {
    @Test void gameStartsAtZeroScode() {
        Bowling sut = new Bowling();
        assertEquals(0, sut.playGame(""));
    }
}
